DROP DATABASE if EXISTS db_books;

CREATE DATABASE db_books;
USE db_books;

CREATE TABLE `livros` 
(
    `id`INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `titulo`	VARCHAR(100),
    `descricao`	VARCHAR(1200),
    `autor`	VARCHAR(70),
    `categoria`	VARCHAR(70),
    `preco`	DOUBLE,
    `imagem`	VARCHAR(1000)
);

INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('1', 'A culpa é das estrelas', 'Hazel Grace Lancaster e Augustus Waters são dois adolescentes que se conhecem em um grupo de apoio para pacientes com câncer. Por causa da doença, Hazel sempre descartou a ideia de se envolver amorosamente.', 'John Green', 'Romance', '44.87', 'https://m.media-amazon.com/images/I/41yToN1cOML._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('2', 'O Rei da Terra do Nunca', 'Por dois séculos, todas as mulheres da família Darling desapareciam quando completavam dezoito anos. Às vezes, ficavam longe por um dia, uma semana ou até um mês. Mas sempre retornavam destruídas. Agora, na tarde do aniversário de dezoito anos de Winnie Darling, sua mãe está trancando todas as janelas e portas.', 'Nikki St. Crowe', 'Horror', '55.9', 'https://m.media-amazon.com/images/I/91azxa1ZbTL._SL1500_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('3', 'A Estrada da Noite', 'Uma lenda do rock, o cinquentão Judas Coyne coleciona objetos macabros. Por isso, quando participa de um estranho leilão na internet, não pensa duas vezes antes de fazer uma oferta. O roqueiro arremata um paletó supostamente assombrado pelo espírito do falecido dono. Sempre às voltas com os próprios fantasmas – o pai violento, as mulheres que usou, os colegas de banda que traiu –, Jude não tem medo de encarar mais um.', 'Joe Hill', 'Horror', '52.4', 'https://m.media-amazon.com/images/I/61YkOraZsDL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('4', 'Como eu era antes de você', 'Aos 26 anos, Louisa Clark não tem muitas ambições. Ela mora com os pais, a irmã mãe solteira, o sobrinho pequeno e um avô que precisa de cuidados constantes desde que sofreu um derrame. Trabalha como garçonete num café, um emprego que não paga muito, mas ajuda nas despesas, e namora Patrick, um triatleta que não parece interessado nela. Não que ela se importe.', 'Jojo Moyes', 'Romance', '27', 'https://m.media-amazon.com/images/I/4164h-1qDZL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('5', 'It - A Coisa', 'Durante as férias de 1958, em uma pacata cidadezinha chamada Derry, um grupo de sete amigos começa a ver coisas estranhas. Um conta que viu um palhaço, outro que viu uma múmia. Finalmente, acabam descobrindo que estavam todos vendo a mesma coisa: um ser sobrenatural e maligno que pode assumir várias formas. É assim que Bill, Beverly, Eddie, Ben, Richie, Mike e Stan enfrentam a Coisa pela primeira vez.', 'Stephen King', 'Horror', '84.58', 'https://m.media-amazon.com/images/I/51z0s3GcvwL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('6', 'Corações Congelados', 'Um beijo proibido de um fae pode ser mortal. Naia foi criada à sombra de seu irmão gêmeo, futuro rei, que tem uma mágica de ferro muito mais poderosa do que a dela. Mas Naia tem desejos próprios. Eles despertam quando ela encontra um fae branco quase morrendo no bosque. Ela só ouvira falar deles em histórias; a temida raça que arrasou cidades, matou seus avós, quase livrou a Alúria de humanos — até que eles desapareceram. Agora, quase vinte anos depois, será que eles estão de volta? Será que uma nova guerra está prestes a começar? Mas o fae é evasivo e misterioso — e também sedutor e fascinante, bonito como ela jamais tinha visto. E daí acontece: Naia o beija — e nada mais será o mesmo. ', 'Day Leitao', 'Romance', '81.6', 'https://m.media-amazon.com/images/I/41FeNyt3sYL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('7', 'Simplesmente Acontece', 'Você acha que é possível existir amizade verdadeira entre um homem e uma mulher?O que acontece quando duas pessoas que foram feitas uma para a outra simplesmente não conseguem ficar juntas?Desde crianças, Rosie e Alex viviam juntos. Todo mundo achava que eles tinham nascido para ser um casal. Todo mundo menos eles mesmos. Grandes amigos desde criança, eles se separaram na adolescência, quando Alex se mudou com sua família de Dublin para os Estados Unidos.', 'Cecilia Ahern', 'Romance', '60', 'https://m.media-amazon.com/images/I/51yMwdFTOhL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('8', 'O Exorcista', '“LIVRAI-NOS DE TODO O MAL, AMÉM.”Um fenômeno quase paranormal atingiu o mundo em 1973. Multidões sofreram de náuseas, desmaios, alucinações e calafrios, numa histeria coletiva sem precedentes. Todos aparentemente possuídos por um filme: o já clássico O Exorcista, dirigido por William Friedkin e adaptado do romance que o roteirista Willian Peter Blatty lançara dois anos antes e que completa 45 anos em 2016.Se a ficção consegue ser tão assustadora, imagine o poder contido na história real? Muitos não sabem, mas a obra-prima de W. Peter Blatty não se trata de uma invenção. Ela foi inspirada num fenômeno ainda mais sombrio, desses que a ciência não consegue explicar: um exorcismo de verdade.A história real aconteceu em 1949, e você pode conhecê-la ― se tiver coragem!', 'Thomas B. Allen', 'Horror', '59', 'https://m.media-amazon.com/images/I/514BugWI0cL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('9', 'Percy Jackson e o ladrão de raios', 'Unindo mitologia grega, muita aventura e tramas hilárias, a história de Rick Riordan sobre um adolescente com TDAH que descobre ser filho do deus do mar e precisa navegar entre o mundo humano e o divino se tornou um best-seller e formou uma geração de leitores apaixonados, que até hoje acompanham a saga de Percy e seus amigos. Agora, a Intrínseca relança os cinco livros da série em uma edição com nova arte de capa, muito pedida pelos leitores. As belas ilustrações da artista Victo Ngai acompanham o design da mais nova aventura do semideus, O cálice dos deuses , que chega às livrarias em lançamento mundial no dia 26 de setembro.', 'Rick Riordan', 'Fantasia', '44.92', 'https://m.media-amazon.com/images/I/41vfSDYLYeL._SX342_SY445_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('10', 'As Crônicas de Nárnia - O Leão, a Feiticeira e o Guarda-roupa', 'O Leão, a Feiticeira e o Guarda-roupa conta a história dos irmãos Pedro, Susana, Edmundo e Lúcia Pevensie. Em meio a brincadeiras na casa de um velho professor, eles descobrem um misterioso guarda-roupa que os leva a Nárnia, um reino mágico que sofre de um inverno sem fim desde que Jadis, a temida Feiticeira Branca, tomou o poder. Mas uma antiga profecia ― que envolve justamente quatro crianças, além de um fantástico leão chamado Aslan ― afirma que há esperança para o reino, contanto que se tenha coragem.', 'C S. Lewis', 'Fantasia', '44.92', 'https://m.media-amazon.com/images/I/41WV7uvsJFL._SX342_SY445_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('11', 'O último suspiro ', 'Quando o corpo torturado de uma jovem é encontrado em uma lixeira, com os olhos inchados e as roupas encharcadas de sangue, a Detetive Erika Foster é uma das primeiras a chegar na cena do crime. O problema é que, desta vez, o caso não é dela.Enquanto luta para garantir seu lugar na equipe de investigação, Erika rapidamente encontra uma ligação desse assassinato com um crime não solucionado de uma jovem quatro meses antes. Jogadas em um local semelhante, as duas mulheres têm feridas idênticas e uma incisão fatal na artéria femoral.', 'Robert Bryndza', 'Suspense', '36.57', 'https://m.media-amazon.com/images/I/51vFbH3-7vL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('12', 'A garota do lago', 'Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado.', 'Charlie Donlea', 'Suspense', '26.9', 'https://m.media-amazon.com/images/I/516VOgxwg2L._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('13', 'A rainha Vermelha', 'O mundo de Mare Barrow é dividido pelo sangue: vermelho ou prateado. Mare e sua família são vermelhos: plebeus, humildes, destinados a servir uma elite prateada cujos poderes sobrenaturais os tornam quase deuses. Mare rouba o que pode para ajudar sua família a sobreviver e não tem esperanças de escapar do vilarejo miserável onde mora. Entretanto, numa reviravolta do destino, ela consegue um emprego no palácio real, onde, em frente ao rei e a toda a nobreza, descobre que tem um poder misterioso… Mas como isso seria possível, se seu sangue é vermelho? Em meio às intrigas dos nobres prateados, as ações da garota vão desencadear uma dança violenta e fatal, que colocará príncipe contra príncipe - e Mare contra seu próprio coração.', 'Victoria Aveyard', 'Fantasia', '31.99', 'https://m.media-amazon.com/images/I/41sr7+fVRGL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('14', 'Coraline', 'Certas portas não devem ser abertas. E Coraline descobre isso pouco tempo depois de chegar com os pais à sua nova casa, um apartamento em um casarão antigo ocupado por vizinhos excêntricos e envolto por uma névoa insistente, um mundo de estranhezas e magia, o tipo de universo que apenas Neil Gaiman pode criar.Ao abrir uma porta misteriosa na sala de casa, a menina se depara com um lugar macabro e fascinante. Ali, naquele outro mundo, seus outros pais são criaturas muito pálidas, com botões negros no lugar dos olhos, sempre dispostos a lhe dar atenção, fazer suas comidas preferidas e mostrar os brinquedos mais divertidos.', ' Neil Gaiman ', 'Fantasia', '48.46', 'https://m.media-amazon.com/images/I/51-9DsDM4DL._SY445_SX342_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('15', 'Manual de assassinato para boas garotas', 'Todos em Little Kilton conhecem essa história. Andie Bell, a garota mais bonita e popular da escola, foi assassinada pelo namorado, Sal Singh, que se suicidou após o crime. Na época, não se falava em outra coisa. Cinco anos depois, Pip ainda vê as marcas que a tragédia deixou na cidade, desde as matérias tendenciosas da imprensa local até o ostracismo da família das vítimas.', 'Holly Jackson', 'Suspense', '44.92', 'https://m.media-amazon.com/images/I/71fE-JgveUL._SL1500_.jpg');
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `categoria`, `preco`, `imagem`) VALUES ('16', 'Bird Box', 'Quatro anos depois de as mortes terem começado, há poucos sobreviventes em Michigan. Malorie e seus dois filhos pequenos estão entre eles. O trio faz parte do grupo que tenta resistir em um mundo no qual abrir os olhos pode ser fatal. Vivendo em uma casa abandonada, Malorie e os filhos não sabem o que se passa do lado de fora. Sempre com as janelas e portas cobertas e sem comunicação com o exterior, o local é uma área isolada no meio do caos. Até o momento em que uma misteriosa neblina atinge a região e Malorie toma uma decisão que adiou por muito tempo.', 'Josh MalermanJosh Malerman', 'Suspense', '18.9', 'https://m.media-amazon.com/images/I/41p4DHosvDL._SY445_SX342_.jpg');
